In [22]:
import numpy as np

In [23]:
def svd(matrix, tolerance=1e-10, max_iterations=1000):
    # Step 1: Compute A^TA
    ata = matrix.T @ matrix

    print("matrix shape:", matrix.shape)
    print("ata shape:", ata.shape)
    
    # Step 2: Eigenvalues and eigenvectors of A^TA
    eigenvalues, eigenvectors = eig(ata)
    
    # Step 3: Compute V
    v = eigenvectors

    print("eigenvectors:", eigenvectors.shape)
    
    # Step 4: Compute singular values and Sigma
    print(f"{eigenvalues=}")
    singular_values = np.sqrt(np.abs(eigenvalues))
    sigma = np.diag(singular_values)
    
    # Step 5: Compute U
    u = np.zeros_like(matrix)
    for i in range(len(singular_values)):
        if singular_values[i] > tolerance:
            u[:, i] = (matrix @ v[:, i]) / singular_values[i]
    
    return u, sigma, v.T

In [24]:
def eig(matrix, num_iterations=1000, tolerance=1e-10):
    n = matrix.shape[0]
    eigenvectors = np.eye(n)

    for _ in range(num_iterations):
        # QR decomposition
        q, r = np.linalg.qr(matrix)

        # Update matrix with RQ decomposition
        matrix = r @ q

        # Accumulate eigenvectors
        eigenvectors = eigenvectors @ q

        # Check for convergence
        off_diagonal_sum = np.sum(np.abs(matrix - np.diag(np.diagonal(matrix))))
        if off_diagonal_sum < tolerance:
            break

    # Extract eigenvalues and eigenvectors
    eigenvalues = np.diag(matrix)
    
    return eigenvalues, eigenvectors

In [25]:
# Example usage:
A = np.array([[3, 2, 2],
              [2, 3, -2]])

U, Sigma, VT = np.linalg.svd(A)

print("U:")
print(U)

print("\nSigma:")
print(Sigma)

print("\nV^T:")
print(VT)


U:
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]

Sigma:
[5. 3.]

V^T:
[[-7.07106781e-01 -7.07106781e-01 -6.47932334e-17]
 [-2.35702260e-01  2.35702260e-01 -9.42809042e-01]
 [-6.66666667e-01  6.66666667e-01  3.33333333e-01]]


In [26]:
# Example usage:
A = np.array([[3, 2, 2],
              [2, 3, -2]])

U, Sigma, VT = svd(A)

print("U:")
print(U)

print("\nSigma:")
print(Sigma)

print("\nV^T:")
print(VT)


matrix shape: (2, 3)
ata shape: (3, 3)
eigenvectors: (3, 3)
eigenvalues=array([ 2.50000000e+01,  9.00000000e+00, -3.33290474e-15])
U:
[[0 0 0]
 [0 0 0]]

Sigma:
[[5.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 3.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 5.77313151e-08]]

V^T:
[[-7.07106781e-01 -7.07106781e-01 -2.54024548e-12]
 [-2.35702260e-01  2.35702260e-01 -9.42809042e-01]
 [-6.66666667e-01  6.66666667e-01  3.33333333e-01]]
